use_default_settings: true

general:
  debug: false
  instance_name: "SearXNG Bionic Agents"

server:
  secret_key: "searxng-bionic-agent-secret-token"
  limiter: false
  image_proxy: true

search:
  safe_search: 0
  autocomplete: "duckduckgo"
  formats:
    - html
    - json
